services:
  app:
    command: python -m pytest -vv test/
    build:
      target: test
    environment:
      TEST_DB_URI: postgresql://test:test@db:5432/test
      SECRET_KEY: "TEST SECRET KEY"
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
