version: '3.4'

services:
  app:
    command: bash -c "python3 /film_library/run.py"
    restart: always
    build:
      context: .
    ports:
      - '5000:5000'
    volumes:
      - ./film_library:/film_library
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      TEST_DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db:
