services:
  app:
    command: bash -c "python3 /film_library/run.py"
    build:
      target: base
    ports:
      - '5000:5000'
    volumes:
      - ./film_library:/film_library
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      DEV_DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  db:
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]

volumes:
  db:
