version: '2.1'

services:
  app:
    command: bash -c "python3 /film_library/run.py"
    restart: always
    build:
      context: .
    ports:
      - '5000:5000'
    volumes:
      - ./film_library:/film_library
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      DEV_DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 10
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]

volumes:
  db:
